version: '3.8'

services:
  learnswing:
    build: .
    container_name: learnswing-app
    # For GUI applications, we need to mount the X11 socket and set display
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority:rw
    network_mode: host
    # Allow X11 forwarding
    security_opt:
      - seccomp:unconfined
    # For Windows users, you might need additional configuration
    # privileged: true
